spring.application.name=social_app


spring.datasource.url = jdbc:mysql://localhost:3306/social
spring.datasource.username=root
spring.datasource.password=Bomysql06@@@@


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
