spring.application.name=social_app


spring.datasource.url = jdbc:mysql://localhost:3306/social
spring.datasource.username=root
spring.datasource.password=Bomysql06@@@@


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

cloudinary.apiName=dhxv199le
cloudinary.apiKey=434738959413396
cloudinary.apiSecret=5ANwNWzpxh6gPGnYbH0lGQou_pM


#spring allow upload file <=1MB so we config here to expand it.
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB

logging.level.org.springframework.security=DEBUG


logging.level.social_app.example.social_app.ws=DEBUG
logging.level.com.ws.socialapp = DEBUG
