spring.application.name=social_app


spring.datasource.url = jdbc:mysql://localhost:3306/social_app
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update